quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/learning_platform
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8082

quarkus.oidc.auth-server-url=http://localhost:8180/realms/learning_platform
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=dmDytZrUjGnb6JdxPeuIIsN6A1KmZfjV
quarkus.oidc.application-type=service

quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=realm_access/roles

quarkus.http.auth.permission.public.paths=/student/getTimezoneByIP
quarkus.http.auth.permission.public.policy=permit

quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated