quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/learning_platform
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8082

//keycloak
quarkus.oidc.auth-server-url=http://localhost:8180/realms/learning_platform
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=zWI650FRX8gdC2yp4pueN63BsdL2x4dr
quarkus.oidc.application-type=service

quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=realm_access/roles

quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated