quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/learning_platform
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8082